#    _____            __ _  __   ____ _____  _
#   / ____|          / _| | \ \ / /_ |  __ \| |
#  | |     _ __ __ _| |_| |_ \ V / | | |__) | |_   _ ___
#  | |    | '__/ _` |  _| __| > <  | |  ___/| | | | / __|
#  | |____| | | (_| | | | |_ / . \ | | |    | | |_| \__ \
#   \_____|_|  \__,_|_|  \__/_/ \_\|_|_|    |_|\__,_|___/


#Permissões craftx1.admin e craftx1.user

Usar-mysql: true
host: '127.0.0.1' #Host do banco de dados.
servidor: 'database' #Banco que será criada as tabelas.
usuario: 'root' #Usuario do banco.
senha: '' #Senha do banco.
porta: '3306' #Porta de conexão.

#usar multiverse-core?
multiverse-hook: true

#Caso true, player pode escolher o valor que quer apostar. Ex: /x1 desafiar Player insano 1000000
x1-ValorMaximo: 5000000

#Custo do x1 padrão.
x1-Custo: 51000
#Premio do x1 padrão.
x1-Premio: 100000
#Valor de empate padrão.
x1-Empate: 51000

TempoEspera: 8 #Em segundos
CancelarPedido: 120
TempoParaIniciar: 8
#Tempo para x1 predefinido para os tipos
#Normal = 15 minutos, hard = 30 minutos, insano = até a derrota de um dos competidores
Normal: 900
Hard: 1600

#Numero maximo de players em x1 de clans
MaxPlayers: 3
#Iniciar o x1 de clans sem o numero maximo de players
Iniciar-Sem-Max: false

#Quando estiver na sala de espera não poderá se mover
Ativar-Bloqueador-De-Movimentos: true

#Quando estiver em um x1 não podera usar nenhum comando
Ativar-Bloqueador-De-Comandos: true

ComandosPermitidos:
 - '/global'
 - '/g'
 - '/helpop'

# Caso ativado, player pode comprar 1 baú, no qual os itens dropados do adversario quando derrotado
# Servirá como um inventário extra
# o bau possui 6 upgrades, cada um com um preço ajustavél, cada level adciona 9 slots
Ativar-Compra-De-Baus: true
upgrade-1: 5000000
upgrade-2: 10000000
upgrade-3: 15000000
upgrade-4: 20000000
upgrade-5: 25000000
upgrade-6: 30000000

Extras:
 Ativar-Limitador-De-Clans: true
 Player-Por-Clan: 9
 Ally-Por-Clan: 2