name: CraftX1Plus
version: 1.3.5
main: me.floydz69.CraftX1Plus.CraftPlus
author: Floydz69
depend: [Vault, SimpleClans]

commands:
    x1:
      description: Use /x1 desafiar [player] [normal/hard/insano] -[aposta]
      permission: craftx1.user
      permission-message: §cYou don't have permission for this.

    x1admin:
      aliases: [x1adm, x1a]
      description: Use para comandos de admin
      permission: craftx1.admin
      permission-message: §cYou don't have permission for this.

    x1clan:
      description: Use /x1clan desafiar [clan]
      permission: craftx1.user
      permission-message: §cYou don't have permission for this.

permissions:
        craftx1.user:
            default: true
        craftx1.admin:
            default: op